# SPDX-FileCopyrightText: 2026 Srijan229
# SPDX-License-Identifier: Apache-2.0
# SPDX-PackageName: rai-toolkit

"""Version parity for installed packages, source checkouts, and reports."""

import json
import subprocess
import sys
from dataclasses import replace
from html import escape
from importlib.metadata import version
from pathlib import Path

import rai_toolkit
from rai_toolkit.assessment import AssessmentResult


def _result():
    return AssessmentResult(
        model_name="offline-stub",
        preset="general",
        run_id="version-test",
        started_at="2026-01-01T00:00:00+00:00",
        duration_seconds=0.0,
        overall_score=1.0,
        overall_passed=True,
        evaluation_overall_score=1.0,
        evaluation_overall_passed=True,
        score_breakdown={},
        verdict_rationale=[],
        frameworks=[],
        policy_violations=[],
        redteam_summary=None,
        evaluation_summary={},
        content_hash="version-test",
    )


def test_distribution_version_matches_public_import():
    assert rai_toolkit.__version__ == version("rai-toolkit")


def _check_reports(result, expected, tmp_path):
    assert result.toolkit_version == expected
    assert result.to_dict()["toolkit_version"] == expected
    json_path = tmp_path / "report.json"
    result.to_json(json_path)
    assert json.loads(json_path.read_text(encoding="utf-8"))["toolkit_version"] == expected
    html_path = tmp_path / "report.html"
    rendered = result.to_html(html_path)
    assert f"Generated by rai-toolkit v{escape(expected)}" in rendered
    assert html_path.read_text(encoding="utf-8") == rendered


def test_assessment_and_reports_use_public_version(tmp_path):
    _check_reports(_result(), rai_toolkit.__version__, tmp_path)


def test_reports_preserve_explicit_version(tmp_path):
    historical = "historical<&>"
    _check_reports(replace(_result(), toolkit_version=historical), historical, tmp_path)


def test_source_checkout_without_distribution_metadata(tmp_path):
    # A fresh process ensures package imports are not satisfied from sys.modules.
    script = """
import importlib.metadata
import runpy
import sys
from pathlib import Path
from unittest.mock import patch

root, test_file, output = map(Path, sys.argv[1:])
sys.path.insert(0, str(root))
authority = runpy.run_path(str(root / 'rai_toolkit' / '_version.py'))['__version__']
original = importlib.metadata.Distribution.from_name
def without_toolkit(name):
    if name.replace('_', '-').lower() == 'rai-toolkit':
        raise importlib.metadata.PackageNotFoundError(name)
    return original(name)

with patch.object(importlib.metadata.Distribution, 'from_name', side_effect=without_toolkit):
    try:
        importlib.metadata.version('rai-toolkit')
    except importlib.metadata.PackageNotFoundError:
        pass
    else:
        raise AssertionError('toolkit metadata must be unavailable')
    import rai_toolkit
    assert rai_toolkit.__version__ == authority
    checks = runpy.run_path(str(test_file))
    checks['test_assessment_and_reports_use_public_version'](output)
"""
    subprocess.run(
        [sys.executable, "-c", script, str(Path(__file__).resolve().parents[1]),
         str(Path(__file__).resolve()), str(tmp_path)],
        cwd=tmp_path,
        check=True,
        capture_output=True,
        text=True,
    )
